/* 지역정보 */
DROP TABLE LOCAL_INFO 
	CASCADE CONSTRAINTS;
/* 비콘지역정보 */
DROP TABLE REGION_INFO 
	CASCADE CONSTRAINTS;

/* 지역정보 */
CREATE TABLE LOCAL_INFO (
	LOCAL_NO INTEGER NOT NULL, /* 지역번호 */
	MANAGER_ID VARCHAR(255), /* 관리자ID */
	LOCAL_NAME VARCHAR2(50) NOT NULL, /* 지역이름 */
	LATITUDE VARCHAR2(255) NOT NULL, /* 위도 */
	LONGITUDE VARCHAR2(255) NOT NULL, /* 경도 */
	ALTITUDE VARCHAR2(255) NOT NULL /* 고도 */
);

/* 비콘지역정보 */
CREATE TABLE REGION_INFO (
	REGION_NO INTEGER NOT NULL, /* 비콘번호 */
	REGION_NAME VARCHAR2(50) NOT NULL, /* 비콘지역이름 */
	UUID VARCHAR2(255) NOT NULL, /* UUID */
	MAJOR INTEGER NOT NULL, /* major */
	MINOR INTEGER NOT NULL, /* minor */
	LOCAL_NO INTEGER NOT NULL /* 지역번호 */
);
