-- 지역정보
ALTER TABLE `LOCAL_INFO`
	DROP FOREIGN KEY `FK_MANAGER_INFO_TO_LOCAL_INFO`; -- 관리자정보 -> 지역정보

-- 지역정보
ALTER TABLE `LOCAL_INFO`
	DROP PRIMARY KEY; -- 지역정보 기본키

-- 비콘지역정보
ALTER TABLE `REGION_INFO`
	DROP PRIMARY KEY; -- 비콘지역정보 기본키

-- 관리자정보
ALTER TABLE `MANAGER_INFO`
	DROP PRIMARY KEY; -- 관리자정보 기본키

-- 사용자정보
ALTER TABLE `USER_INFO`
	DROP PRIMARY KEY; -- 사용자정보 기본키

-- 지역정보
DROP TABLE IF EXISTS `LOCAL_INFO` RESTRICT;

-- 비콘지역정보
DROP TABLE IF EXISTS `REGION_INFO` RESTRICT;

-- 관리자정보
DROP TABLE IF EXISTS `MANAGER_INFO` RESTRICT;

-- 사용자정보
DROP TABLE IF EXISTS `USER_INFO` RESTRICT;

-- 지역정보
CREATE TABLE `LOCAL_INFO` (
	`LOCAL_NO`   INTEGER      NOT NULL COMMENT '지역번호', -- 지역번호
	`MANAGER_ID` VARCHAR(255) NULL     COMMENT '관리자ID', -- 관리자ID
	`LOCAL_NAME` VARCHAR(50)  NOT NULL COMMENT '지역이름', -- 지역이름
	`LATITUDE`   VARCHAR(255) NOT NULL COMMENT '위도', -- 위도
	`LONGITUDE`  VARCHAR(255) NOT NULL COMMENT '경도', -- 경도
	`ALTITUDE`   VARCHAR(255) NOT NULL COMMENT '고도', -- 고도
	`AREA_NAME`  VARCHAR(50)  NOT NULL COMMENT '광역이름' -- 광역이름
)
COMMENT '지역정보';

-- 지역정보
ALTER TABLE `LOCAL_INFO`
	ADD CONSTRAINT `PK_LOCAL_INFO` -- 지역정보 기본키
		PRIMARY KEY (
			`LOCAL_NO` -- 지역번호
		);

ALTER TABLE `LOCAL_INFO`
	MODIFY COLUMN `LOCAL_NO` INTEGER NOT NULL AUTO_INCREMENT COMMENT '지역번호';

ALTER TABLE `LOCAL_INFO`
	AUTO_INCREMENT = 1;

-- 비콘지역정보
CREATE TABLE `REGION_INFO` (
	`REGION_NO`   INTEGER      NOT NULL COMMENT '비콘번호', -- 비콘번호
	`REGION_NAME` VARCHAR(50)  NOT NULL COMMENT '비콘지역이름', -- 비콘지역이름
	`UUID`        VARCHAR(255) NOT NULL COMMENT 'UUID', -- UUID
	`MAJOR`       INTEGER      NOT NULL COMMENT 'major', -- major
	`MINOR`       INTEGER      NOT NULL COMMENT 'minor' -- minor
)
COMMENT '비콘지역정보';

-- 비콘지역정보
ALTER TABLE `REGION_INFO`
	ADD CONSTRAINT `PK_REGION_INFO` -- 비콘지역정보 기본키
		PRIMARY KEY (
			`REGION_NO` -- 비콘번호
		);

ALTER TABLE `REGION_INFO`
	MODIFY COLUMN `REGION_NO` INTEGER NOT NULL AUTO_INCREMENT COMMENT '비콘번호';

ALTER TABLE `REGION_INFO`
	AUTO_INCREMENT = 1;

-- 관리자정보
CREATE TABLE `MANAGER_INFO` (
	`MANAGER_ID` VARCHAR(255) NOT NULL COMMENT '관리자ID', -- 관리자ID
	`LACAL_NO`   INTEGER      NULL     COMMENT '지역번호' -- 지역번호
)
COMMENT '관리자정보';

-- 관리자정보
ALTER TABLE `MANAGER_INFO`
	ADD CONSTRAINT `PK_MANAGER_INFO` -- 관리자정보 기본키
		PRIMARY KEY (
			`MANAGER_ID` -- 관리자ID
		);

-- 사용자정보
CREATE TABLE `USER_INFO` (
	`USER_ID`       VARCHAR(255) NOT NULL COMMENT '사용자ID', -- 사용자ID
	`MOBILE_INFO`   VARCHAR(255) NOT NULL COMMENT '기기정보', -- 기기정보
	`LANGUAGE_INFO` VARCHAR(255) NULL     COMMENT '언어정보' -- 언어정보
)
COMMENT '사용자정보';

-- 사용자정보
ALTER TABLE `USER_INFO`
	ADD CONSTRAINT `PK_USER_INFO` -- 사용자정보 기본키
		PRIMARY KEY (
			`USER_ID` -- 사용자ID
		);

-- 지역정보
ALTER TABLE `LOCAL_INFO`
	ADD CONSTRAINT `FK_MANAGER_INFO_TO_LOCAL_INFO` -- 관리자정보 -> 지역정보
		FOREIGN KEY (
			`MANAGER_ID` -- 관리자ID
		)
		REFERENCES `MANAGER_INFO` ( -- 관리자정보
			`MANAGER_ID` -- 관리자ID
		);