DROP INDEX PK_REGION_INFO;

DROP INDEX PK_LOCAL_INFO;

DROP INDEX PK_USER_INFO;

DROP INDEX PK_DATA_INFO;

DROP INDEX PK_MANAGER_INFO;

/* 비콘지역정보 */
DROP TABLE REGION_INFO 
	CASCADE CONSTRAINTS;

/* 지역정보 */
DROP TABLE LOCAL_INFO 
	CASCADE CONSTRAINTS;

/* 사용자정보 */
DROP TABLE USER_INFO 
	CASCADE CONSTRAINTS;

/* 자료정보 */
DROP TABLE DATA_INFO 
	CASCADE CONSTRAINTS;

/* 관리자정보 */
DROP TABLE MANAGER_INFO 
	CASCADE CONSTRAINTS;

/* 비콘지역정보 */
CREATE TABLE REGION_INFO (
	REGION_NO INTEGER NOT NULL, /* 비콘번호 */
	REGION_NAME VARCHAR2(50) NOT NULL, /* 비콘지역이름 */
	UUID VARCHAR2(255) NOT NULL, /* UUID */
	MAJOR INTEGER NOT NULL, /* major */
	MINOR INTEGER NOT NULL, /* minor */
	LOCAL_NO INTEGER NOT NULL /* 지역번호 */
);

COMMENT ON TABLE REGION_INFO IS '비콘지역정보';

COMMENT ON COLUMN REGION_INFO.REGION_NO IS '비콘번호';

COMMENT ON COLUMN REGION_INFO.REGION_NAME IS '비콘지역이름';

COMMENT ON COLUMN REGION_INFO.UUID IS 'UUID';

COMMENT ON COLUMN REGION_INFO.MAJOR IS 'major';

COMMENT ON COLUMN REGION_INFO.MINOR IS 'minor';

COMMENT ON COLUMN REGION_INFO.LOCAL_NO IS '지역번호';

CREATE UNIQUE INDEX PK_REGION_INFO
	ON REGION_INFO (
		REGION_NO ASC
	);

ALTER TABLE REGION_INFO
	ADD
		CONSTRAINT PK_REGION_INFO
		PRIMARY KEY (
			REGION_NO
		);

/* 지역정보 */
CREATE TABLE LOCAL_INFO (
	LOCAL_NO INTEGER NOT NULL, /* 지역번호 */
	MANAGER_ID VARCHAR(255), /* 관리자ID */
	LOCAL_NAME VARCHAR2(50) NOT NULL, /* 지역이름 */
	LATITUDE VARCHAR2(255) NOT NULL, /* 위도 */
	LONGITUDE VARCHAR2(255) NOT NULL, /* 경도 */
	ALTITUDE VARCHAR2(255) NOT NULL /* 고도 */
);

COMMENT ON TABLE LOCAL_INFO IS '지역정보';

COMMENT ON COLUMN LOCAL_INFO.LOCAL_NO IS '지역번호';

COMMENT ON COLUMN LOCAL_INFO.MANAGER_ID IS '관리자ID';

COMMENT ON COLUMN LOCAL_INFO.LOCAL_NAME IS '지역이름';

COMMENT ON COLUMN LOCAL_INFO.LATITUDE IS '위도';

COMMENT ON COLUMN LOCAL_INFO.LONGITUDE IS '경도';

COMMENT ON COLUMN LOCAL_INFO.ALTITUDE IS '고도';

CREATE UNIQUE INDEX PK_LOCAL_INFO
	ON LOCAL_INFO (
		LOCAL_NO ASC
	);

ALTER TABLE LOCAL_INFO
	ADD
		CONSTRAINT PK_LOCAL_INFO
		PRIMARY KEY (
			LOCAL_NO
		);

/* 사용자정보 */
CREATE TABLE USER_INFO (
	USER_ID VARCHAR(255) NOT NULL, /* 사용자id */
	MOBILE_INFO VARCHAR2(255) NOT NULL, /* 기기정보 */
	LANGUAGE_INFO VARCHAR2(255) /* 언어정보 */
);

COMMENT ON TABLE USER_INFO IS '사용자정보';

COMMENT ON COLUMN USER_INFO.USER_ID IS '사용자id';

COMMENT ON COLUMN USER_INFO.MOBILE_INFO IS '기기정보';

COMMENT ON COLUMN USER_INFO.LANGUAGE_INFO IS '언어정보';

CREATE UNIQUE INDEX PK_USER_INFO
	ON USER_INFO (
		USER_ID ASC
	);

ALTER TABLE USER_INFO
	ADD
		CONSTRAINT PK_USER_INFO
		PRIMARY KEY (
			USER_ID
		);

/* 자료정보 */
CREATE TABLE DATA_INFO (
	DATA_NO INTEGER NOT NULL, /* 자료번호 */
	DATA_PATH VARCHAR(255) NOT NULL, /* 파일경로 */
	DATA_TYPE INTEGER NOT NULL, /* 자료타입 */
	LOCAL_NO INTEGER NOT NULL, /* 지역번호 */
	REGION_NO INTEGER /* 비콘번호 */
);

COMMENT ON TABLE DATA_INFO IS '자료정보';

COMMENT ON COLUMN DATA_INFO.DATA_NO IS '자료번호';

COMMENT ON COLUMN DATA_INFO.DATA_PATH IS '파일경로';

COMMENT ON COLUMN DATA_INFO.DATA_TYPE IS '자료타입';

COMMENT ON COLUMN DATA_INFO.LOCAL_NO IS '지역번호';

COMMENT ON COLUMN DATA_INFO.REGION_NO IS '비콘번호';

CREATE UNIQUE INDEX PK_DATA_INFO
	ON DATA_INFO (
		DATA_NO ASC
	);

ALTER TABLE DATA_INFO
	ADD
		CONSTRAINT PK_DATA_INFO
		PRIMARY KEY (
			DATA_NO
		);

/* 관리자정보 */
CREATE TABLE MANAGER_INFO (
	MANAGER_ID VARCHAR(255) NOT NULL, /* 관리자ID */
	LOCAL_NO INTEGER /* 지역번호 */
);

COMMENT ON TABLE MANAGER_INFO IS '관리자정보';

COMMENT ON COLUMN MANAGER_INFO.MANAGER_ID IS '관리자ID';

COMMENT ON COLUMN MANAGER_INFO.LOCAL_NO IS '지역번호';

CREATE UNIQUE INDEX PK_MANAGER_INFO
	ON MANAGER_INFO (
		MANAGER_ID ASC
	);

ALTER TABLE MANAGER_INFO
	ADD
		CONSTRAINT PK_MANAGER_INFO
		PRIMARY KEY (
			MANAGER_ID
		);

ALTER TABLE REGION_INFO
	ADD
		CONSTRAINT FK_LOCAL_INFO_TO_REGION_INFO
		FOREIGN KEY (
			LOCAL_NO
		)
		REFERENCES LOCAL_INFO (
			LOCAL_NO
		);

ALTER TABLE LOCAL_INFO
	ADD
		CONSTRAINT FK_MANAGER_INFO_TO_LOCAL_INFO
		FOREIGN KEY (
			MANAGER_ID
		)
		REFERENCES MANAGER_INFO (
			MANAGER_ID
		);

ALTER TABLE DATA_INFO
	ADD
		CONSTRAINT FK_LOCAL_INFO_TO_DATA_INFO
		FOREIGN KEY (
			LOCAL_NO
		)
		REFERENCES LOCAL_INFO (
			LOCAL_NO
		);

ALTER TABLE DATA_INFO
	ADD
		CONSTRAINT FK_REGION_INFO_TO_DATA_INFO
		FOREIGN KEY (
			REGION_NO
		)
		REFERENCES REGION_INFO (
			REGION_NO
		);